---
output: 
  pdf_document:
    keep_tex: true
bibliography: moose_parasites.bib
---

\vspace*{\stretch{1.0}}
\begin{center}
  \Large{\textbf{Evaluation of infection risk of two endoparasites to moose (Alces alces) in the Adirondack Park of New York}}\\
  \vspace{5mm}
  \large{Alec Wong\textsuperscript{1}, Krysten Schuler\textsuperscript{1}, Angela Fuller\textsuperscript{1,2,3}}\\
  \vspace{5mm}
  \normalsize{\textsuperscript{1}Cornell University}\\
  \normalsize{\textsuperscript{2}New York Cooperative Fish and Wildlife Research Unit}\\
  \normalsize{\textsuperscript{3}U.S. Geological Survey}\\
  \vspace*{\fill}
\end{center}

\newpage

# Abstract

Endoparasites *Parelaphastrongylus tenuis* and *Fascioloides magna* were
attributed to 19% and 21% of mortalities in New York in 2015, respectively, and
may be contributing factors to limiting moose (*Alces alces*) populations in the
Adirondacks region. Field surveys were conducted to collect white-tailed deer
(*Odocoileus virginianus*) fecal pellets under distance sampling protocol both
to measure relative deer density and to diagnose the infection status of the
pellets by *P. tenuis* and *F. magna*. Over the three years of data collection,
40.9% of fecal pellets collected contained *F. magna* eggs, and 34.7% of fecal
pellets contained L1 *P. tenuis* larvae ($N=622$). We attempted to quantify the
geospatial distribution of parasite infection using landscape variables such as
habitat, geomorphon structure, elevation, and spatial trend, but goodness-of-fit
tests indicated poor fit of the model structures we evaluated, whether assessed
as continuous intensity of infection (Poisson, negative binomial, zero-inflated
Poisson), or binary infection status (binomial). We conclude that the data are
not extensive enough to quantify relationships between parasite infection in
white-tailed deer fecal pellets and geospatial effects.

# Introduction

Moose (*Alces alces*) populations are in decline in parts of their range in
North America such as in Minnesota, Vermont, and New Hampshire in the United
States of America and Nova Scotia, Alberta, Saskatchewan, Manitoba, and Ontario
in Canada [@Lankester2018; @Timmermann2017]. Some researchers point to parasite
infection from liver fluke (*Fascioloides magna*) and/or brainworm
(*Parelaphastrongylus tenuis*) as contributing factors to these declines
[@Murray2006; @Lankester2010; @Lankester2018; @Wunschmann2015], although this
claim is controversial [@Lenarz2009] and in some areas may coincide with other
factors such as depredation or low reproduction rates that may disguise effects
of parasite infection [@SHANNONBARBERMEYER2016; @Kuzyk2018]. Nevertheless, brain
worm and liver fluke cause morbidity and mortality in moose populations and
should be monitored.

Infections by *P. tenuis* are benign to white-tailed deer (*Odocoileus
virginianus*), but cause severe neurological disorders in moose caused by
migration of larvae through the central nervous system that often end in death
[@Pybus2001; @Lankester2010]. *Parelaphastrongylus tenuis* is acquired via
ingestion of gastropod intermediate hosts, in which *P. tenuis* larvae have molt
from L1 to L2, and L3 stages over approximately 4 weeks. Gastropods become
infected by ingesting the mucuosal layer surrounding white-tailed deer fecal
pellets, or from the soil over which the L1-stage larvae have been washed by
precipitation.

*Fascioloides magna* infection damage manifests as lesions in the hepatic tissue
due to migration of immature flukes or fibrous encapsulation of adult flukes
[@Pybus2001]. Again, moose are thought to become infected through ingestion of
gastropod intermediate hosts. A major distinction is that the gastropod hosts
are aquatic snails (typically within the genus *Lymnaea*) that become infected
by free-swimming miracidia introduced to the water as eggs in white-tailed deer
feces [@Pybus2001; @Peterson2013; @Malcicka2015]. The meracidia develop within
the snail, ultimately generating cercariae that encyst as metacercariae on
aquatic vegetation. Because moose select aquatic vegetation as a significant
proportion of their diet, *F. magna* metacercariae are presumably commonly
consumed by moose.

In the Adirondacks of New York, moose populations have increased since their
extirpation in the late 19th century, but their populations have not seen the
same growth during the 20th century as their New England counterparts
[@Timmermann2017]. Recent estimates of moose population size indicate that there
are approximately 600 to 1000 moose in the Adirondacks [@Wong2019], a range
which does not indicate substantial change from previous assertions of
population size [@Hickey2008]. Factors that may be limiting the population are
not established, but the focal parasites *P. tenuis* and *F. magna* have been
observed in moose necropsies with moderate frequency (REF Schuler and/or DEC).

The New York State Department of Environmental Conservation (DEC) has been
gathering information on moose health from incidental mortalities (n = 117)
since 2000 and the Animal Health Diagnostic Center (AHDC) started live moose
testing in 2015. Moose in New York State appear to be substantially impacted by
several parasites excepting winter ticks, which are more common in New England
states. Over 19% of mortalities were attributed to P. tenuis, 21% of moose
carcasses examined were infected with liver flukes (Fascioloides magna).
Migrating parasites cannot be detected in live moose, but were likely a problem
as New York moose had 5-6x higher eosinophil (white blood cell) counts than New
Hampshire or Maine moose.

The geospatial distribution of infection risk to moose is a concern for
management, and this 

# Materials and Methods

## Study area

We surveyed within the Adirondack Park of the state of New York. It is an area
of approximately 24,000 $\text{km}^2$, composing approximately 17% of the state
of New York. Elevation ranges from 100m - 1600m. The Adirondack Park contains
primarily upland forest habitat dominated by such species as American beech
(*Fagus grandifolia*), red spruce (*Picea rubens*), hemlock (*Tsuga
canadensis*), sugar maple (*Acer saccharum*), striped maple (*Acer
pensylvanicum*), and balsam fir (*Abies balsamea*). Approximately 20% of the
park is composed of wetland habitats including open river corridors, floating
bogs, and large open bogs dominated by conifers [@Hickey2008].

## Field data collection

White-tailed deer fecal pellet groups were collected opportunistically during
the years of 2016 and 2017 for the purpose of parasite quantification during a
larger survey investigating the population size of moose in the park. The moose
study surveyed triangular transects approximately 3 km long, selected by cluster
random sampling. The clustering design of the transects were optimized for a
spatial capture-recapture survey, including 3 transects per cluster separated by
approximately 2-4 km. **INSERT FIGURE FOR MOOSE TRANSECTS**

In 2018, a single-observer distance sampling protocol was implemented to
quantify deer fecal group abundance in addition to measuring parasite intensity.
Along each moose transects, 6 distance sampling transects each 100m long were
spaced 200m apart from each other. **INSERT FIGURE FOR DEER TRANSECTS** A total
of **N** transects were sampled in 2018. At the specified start point, field
technicians extended a 100m tape to serve as the center line, and made
observations along its length. Any number of scat pellets were considered to
constitute a fecal group, and the approximate number was recorded. When a fecal
group was detected, its distance perpendicular from the center line, and
parallel along the center line was recorded. The perpendicular distance is the
focal variable of distance sampling, but the parallel distance provided highly
precise location coordinates of the scats -- because the start point of the
transect was recorded with greater accuracy (due to longer GPS averaging time),
the coordinates of the scats could be refined by translating the start point in
space by the angle of the transect, and the parallel distance away from the
start point.

Fifty-seven white-tailed deer fecal samples were collected in 2016, 391 samples
were collected in 2017, and 174 samples were collected in 2018.

## Parasitological analyses

The fecal samples were analyzed by the Cornell Animal Health and Diagnostic
Center using several methods. For *F. magna*, Flukefinder, a modified Baermann
technique, and fecal quantitative flotation were used. For *P. tenuis*, the
modified Baermann, and fecal quantitative flotation methods were implemented.
After 2016, the performant method for *F. magna* was determined to be
Flukefinder, and for *P. tenuis* the performant method was the modified Baermann
technique. This was assessed by **HOW? ASK KRYSTEN**, and validated post-hoc to
have the greatest detection probability by an occupancy analysis.

### Flukefinder

*Needs to be updated by relevant members; Flukefinder methodology not in shared folder*

### Modified Baermann

### Fecal flotation

## Statistical Models

For analysis of relative risk of infection to moose, we implemented a
hierarchical Bayesian modeling framework analyzed with the `R` packages `INLA`,
which uses integrated nested Laplace approximation to approximate the posterior
distribution of model parameters. 

### Parasite intensity model

Let $\widehat{\lambda}(s)$ be the estimated per-fecal-group-sample abundance
(or, intensity in the epidemiological sense). Let $S = \{s_i, i = 1, ..., n\}
\subset \Omega$ be the $n$ distinct locations where white-tailed deer fecal
groups were observed within the observation region $\Omega \subseteq
\mathbb{R}^2$, and let $y_i$ be the observed parasite count within the fecal
sample.

Parasites observed within each scat sample are $\ge 0$, and due to the high
prevalence of 0's, we considered a negative binomial distribution in addition to
the Poisson. On any bounded region $B \subseteq \Omega$, observations are thus
modeled as follows:

\begin{equation}
\begin{gathered}
y_i \sim \text{Poisson}(\mu_i) \\
\log(\mu_i) = \beta_0 + \beta_1*x_1(s_i) + ... + \beta_p*x_p(s_i) + \Psi_1(s_i) \\
\Psi_1(s_i) \sim GP(0, \Sigma)
\end{gathered}
\end{equation}

Where, $y_i$ represent the parasites observed per fecal group sample, $\mu_i$ is
the mean function modeled dependent upon spatial covariates $x_j(s)$, and
$\Psi_1(s)$ is a random Gaussian process with mean 0 and covariance matrix
$\Sigma$. The covariance function used is the Matern:

\[
\text{cov}[\Psi(s), \Psi(s')] = \sigma_{\Psi}^2 \  \kappa ||s' - s|| \ \mathcal{K}_1(\kappa ||s' - s||)
\]

where $\tau, \kappa$ are variance and range scaling parameters, respectively,
$\sigma_{\Psi}^2 = 1/(4\pi\kappa^2\tau^2)$ is the marginal variance, and
$\mathcal{K}_1$ is the modified Bessel function of the second kind and order 1
(See @Lindgren2015 for the specific representation and estimation of the spatial
random effects within INLA). The spatial random field is optional and we test
models with and without it to assess support for modeling unstructured spatial
dependence.

#### Priors 

#### Covariates on parasite intensity

In our model, we consider the following covariate effects on parasite intensity.
Coordinate data (UTM Easting and Northing) are included to model broad-scale
spatial trend. We considered a derived variable of precipitation representing
the total accumulation of precipitation in the year prior to the data collection
date, measured in inches. Precipitation affects the survival of *P. tenuis* and
*F. magna* outside of a host (i.e. as L1 larvae, and eggs in feces,
respectively), and so it is anticipated that deer would be more likely to be
infected in areas of higher rainfall [@Pybus2001]. Additionally, gastropod
activity is inhibited by drought, and so higher rainfall would suggest higher
risk of infection due to a higher availability of gastropods to be ingested in
the case of *P. tenuis* [@Lankester2018]. We used the spatially interpolated
PRISM dataset for precipitation [@PRISM]. We considered another derived variable
for snowfall accumulation in the snowfall season prior to the data collection
date (that is, from September until April prior to the date of survey). Similar
to precipitation, we anticipate that areas that experience low snowfall prior to
the survey date will exhibit a higher parasite intensity due to increased
parasite survival, and increased activity of gastropod intermediate hosts. The
National Weather Service's National Snowfall Analysis dataset was used to obtain
spatially-referenced snowfall amounts.

Local terrain basins where water may collect were considered as a potentially
important effect particularly for *F. magna*, as the life cycle of the parasite
has a period during which metacercariae encyst on aquatic vegetation and once
matured infect aquatic snail intermediate hosts. We hypothesized that intensity
of infection for *F. magna* will be greater in basins than on slopes or peaks,
and we assessed this by the geomorphon tool in QGIS, assessed at a resolution of
40km (1600 squared-kilometers). This resolution was selected because it
maximized the variation in the geomorphon value types relative to our sample
locations.


#### Priors



# Results



## Model results

## Bayesian model checks

### Conditional predictive ordinate

### Probability integral transform

# Discussion

# References